server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Prevent caching of runtime config
  location = /config.js {
    add_header Cache-Control "no-store, must-revalidate";
    try_files $uri =404;
  }

  location / {
    try_files $uri /index.html;
  }
}